/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JiraProjectSettingResponse } from '../../models/jira-project-setting-response';

export interface GetJiraProjectSetting$Params {
  projectId: string;
  reload?: boolean;
}

export function getJiraProjectSetting(http: HttpClient, rootUrl: string, params: GetJiraProjectSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<JiraProjectSettingResponse>> {
  const rb = new RequestBuilder(rootUrl, getJiraProjectSetting.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.query('reload', params.reload, {"style":"form"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JiraProjectSettingResponse>;
    })
  );
}

getJiraProjectSetting.PATH = '/api/project/{projectId}/setting/jira';
