/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthConfig } from '../../models/auth-config';

export interface UpdateAuthConfig$Params {
      body?: AuthConfig
}

export function updateAuthConfig(http: HttpClient, rootUrl: string, params?: UpdateAuthConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthConfig>> {
  const rb = new RequestBuilder(rootUrl, updateAuthConfig.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthConfig>;
    })
  );
}

updateAuthConfig.PATH = '/api/config/auth';
