/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addMember } from '../fn/project/add-member';
import { AddMember$Params } from '../fn/project/add-member';
import { AlertSetting } from '../models/alert-setting';
import { deleteProjectMember } from '../fn/project/delete-project-member';
import { DeleteProjectMember$Params } from '../fn/project/delete-project-member';
import { EnvironmentVariable } from '../models/environment-variable';
import { EnvironmentVariablePage } from '../models/environment-variable-page';
import { getIntegrationProject } from '../fn/project/get-integration-project';
import { GetIntegrationProject$Params } from '../fn/project/get-integration-project';
import { getJiraIntegrationProject } from '../fn/project/get-jira-integration-project';
import { GetJiraIntegrationProject$Params } from '../fn/project/get-jira-integration-project';
import { getMailIntegrationProject } from '../fn/project/get-mail-integration-project';
import { GetMailIntegrationProject$Params } from '../fn/project/get-mail-integration-project';
import { getProjectCommits } from '../fn/project/get-project-commits';
import { GetProjectCommits$Params } from '../fn/project/get-project-commits';
import { getProjectEnvironment } from '../fn/project/get-project-environment';
import { GetProjectEnvironment$Params } from '../fn/project/get-project-environment';
import { getProjectFindings } from '../fn/project/get-project-findings';
import { GetProjectFindings$Params } from '../fn/project/get-project-findings';
import { getProjectInfo } from '../fn/project/get-project-info';
import { GetProjectInfo$Params } from '../fn/project/get-project-info';
import { getProjectPackages } from '../fn/project/get-project-packages';
import { GetProjectPackages$Params } from '../fn/project/get-project-packages';
import { getProjects } from '../fn/project/get-projects';
import { GetProjects$Params } from '../fn/project/get-projects';
import { getProjectScanners } from '../fn/project/get-project-scanners';
import { GetProjectScanners$Params } from '../fn/project/get-project-scanners';
import { getProjectScans } from '../fn/project/get-project-scans';
import { GetProjectScans$Params } from '../fn/project/get-project-scans';
import { getProjectSetting } from '../fn/project/get-project-setting';
import { GetProjectSetting$Params } from '../fn/project/get-project-setting';
import { getProjectStatistic } from '../fn/project/get-project-statistic';
import { GetProjectStatistic$Params } from '../fn/project/get-project-statistic';
import { getProjectUsers } from '../fn/project/get-project-users';
import { GetProjectUsers$Params } from '../fn/project/get-project-users';
import { getTeamsIntegrationProject } from '../fn/project/get-teams-integration-project';
import { GetTeamsIntegrationProject$Params } from '../fn/project/get-teams-integration-project';
import { JiraProjectSettingResponse } from '../models/jira-project-setting-response';
import { ProjectCommitSummary } from '../models/project-commit-summary';
import { ProjectFindingPage } from '../models/project-finding-page';
import { ProjectInfo } from '../models/project-info';
import { ProjectIntegration } from '../models/project-integration';
import { ProjectPackagePage } from '../models/project-package-page';
import { ProjectScanner } from '../models/project-scanner';
import { ProjectScanPage } from '../models/project-scan-page';
import { ProjectSetting } from '../models/project-setting';
import { ProjectStatistics } from '../models/project-statistics';
import { ProjectSummaryPage } from '../models/project-summary-page';
import { ProjectUser } from '../models/project-user';
import { ProjectUserPage } from '../models/project-user-page';
import { removeProjectEnvironment } from '../fn/project/remove-project-environment';
import { RemoveProjectEnvironment$Params } from '../fn/project/remove-project-environment';
import { setProjectEnvironment } from '../fn/project/set-project-environment';
import { SetProjectEnvironment$Params } from '../fn/project/set-project-environment';
import { TeamsSetting } from '../models/teams-setting';
import { testTeamsIntegrationProject } from '../fn/project/test-teams-integration-project';
import { TestTeamsIntegrationProject$Params } from '../fn/project/test-teams-integration-project';
import { updateJiraIntegrationProject } from '../fn/project/update-jira-integration-project';
import { UpdateJiraIntegrationProject$Params } from '../fn/project/update-jira-integration-project';
import { updateMailIntegrationProject } from '../fn/project/update-mail-integration-project';
import { UpdateMailIntegrationProject$Params } from '../fn/project/update-mail-integration-project';
import { updateProjectMember } from '../fn/project/update-project-member';
import { UpdateProjectMember$Params } from '../fn/project/update-project-member';
import { updateSastSettingProject } from '../fn/project/update-sast-setting-project';
import { UpdateSastSettingProject$Params } from '../fn/project/update-sast-setting-project';
import { updateScaSettingProject } from '../fn/project/update-sca-setting-project';
import { UpdateScaSettingProject$Params } from '../fn/project/update-sca-setting-project';
import { updateTeamsIntegrationProject } from '../fn/project/update-teams-integration-project';
import { UpdateTeamsIntegrationProject$Params } from '../fn/project/update-teams-integration-project';

@Injectable({ providedIn: 'root' })
export class ProjectService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProjects()` */
  static readonly GetProjectsPath = '/api/project';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjects$Response(params?: GetProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectSummaryPage>> {
    return getProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjects(params?: GetProjects$Params, context?: HttpContext): Observable<ProjectSummaryPage> {
    return this.getProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectSummaryPage>): ProjectSummaryPage => r.body)
    );
  }

  /** Path part for operation `getProjectInfo()` */
  static readonly GetProjectInfoPath = '/api/project/{projectId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectInfo$Response(params: GetProjectInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectInfo>> {
    return getProjectInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectInfo(params: GetProjectInfo$Params, context?: HttpContext): Observable<ProjectInfo> {
    return this.getProjectInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectInfo>): ProjectInfo => r.body)
    );
  }

  /** Path part for operation `getProjectStatistic()` */
  static readonly GetProjectStatisticPath = '/api/project/{projectId}/statistic';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectStatistic()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectStatistic$Response(params: GetProjectStatistic$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectStatistics>> {
    return getProjectStatistic(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectStatistic$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectStatistic(params: GetProjectStatistic$Params, context?: HttpContext): Observable<ProjectStatistics> {
    return this.getProjectStatistic$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectStatistics>): ProjectStatistics => r.body)
    );
  }

  /** Path part for operation `getProjectCommits()` */
  static readonly GetProjectCommitsPath = '/api/project/{projectId}/commit';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectCommits()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectCommits$Response(params: GetProjectCommits$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectCommitSummary>>> {
    return getProjectCommits(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectCommits$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectCommits(params: GetProjectCommits$Params, context?: HttpContext): Observable<Array<ProjectCommitSummary>> {
    return this.getProjectCommits$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProjectCommitSummary>>): Array<ProjectCommitSummary> => r.body)
    );
  }

  /** Path part for operation `getProjectScanners()` */
  static readonly GetProjectScannersPath = '/api/project/{projectId}/scanner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectScanners()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectScanners$Response(params: GetProjectScanners$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectScanner>>> {
    return getProjectScanners(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectScanners$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectScanners(params: GetProjectScanners$Params, context?: HttpContext): Observable<Array<ProjectScanner>> {
    return this.getProjectScanners$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProjectScanner>>): Array<ProjectScanner> => r.body)
    );
  }

  /** Path part for operation `getProjectScans()` */
  static readonly GetProjectScansPath = '/api/project/{projectId}/scan/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectScans()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectScans$Response(params: GetProjectScans$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectScanPage>> {
    return getProjectScans(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectScans$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectScans(params: GetProjectScans$Params, context?: HttpContext): Observable<ProjectScanPage> {
    return this.getProjectScans$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectScanPage>): ProjectScanPage => r.body)
    );
  }

  /** Path part for operation `getProjectFindings()` */
  static readonly GetProjectFindingsPath = '/api/project/{projectId}/finding/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectFindings()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectFindings$Response(params: GetProjectFindings$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectFindingPage>> {
    return getProjectFindings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectFindings$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectFindings(params: GetProjectFindings$Params, context?: HttpContext): Observable<ProjectFindingPage> {
    return this.getProjectFindings$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectFindingPage>): ProjectFindingPage => r.body)
    );
  }

  /** Path part for operation `getProjectPackages()` */
  static readonly GetProjectPackagesPath = '/api/project/{projectId}/package/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectPackages()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectPackages$Response(params: GetProjectPackages$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectPackagePage>> {
    return getProjectPackages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectPackages$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectPackages(params: GetProjectPackages$Params, context?: HttpContext): Observable<ProjectPackagePage> {
    return this.getProjectPackages$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectPackagePage>): ProjectPackagePage => r.body)
    );
  }

  /** Path part for operation `getProjectUsers()` */
  static readonly GetProjectUsersPath = '/api/project/{projectId}/member/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectUsers()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectUsers$Response(params: GetProjectUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectUserPage>> {
    return getProjectUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectUsers$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectUsers(params: GetProjectUsers$Params, context?: HttpContext): Observable<ProjectUserPage> {
    return this.getProjectUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectUserPage>): ProjectUserPage => r.body)
    );
  }

  /** Path part for operation `addMember()` */
  static readonly AddMemberPath = '/api/project/{projectId}/member';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addMember()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMember$Response(params: AddMember$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectUser>> {
    return addMember(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addMember$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addMember(params: AddMember$Params, context?: HttpContext): Observable<ProjectUser> {
    return this.addMember$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectUser>): ProjectUser => r.body)
    );
  }

  /** Path part for operation `updateProjectMember()` */
  static readonly UpdateProjectMemberPath = '/api/project/{projectId}/member/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProjectMember()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProjectMember$Response(params: UpdateProjectMember$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectUser>> {
    return updateProjectMember(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProjectMember$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProjectMember(params: UpdateProjectMember$Params, context?: HttpContext): Observable<ProjectUser> {
    return this.updateProjectMember$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectUser>): ProjectUser => r.body)
    );
  }

  /** Path part for operation `deleteProjectMember()` */
  static readonly DeleteProjectMemberPath = '/api/project/{projectId}/member/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProjectMember()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProjectMember$Response(params: DeleteProjectMember$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProjectMember(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProjectMember$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProjectMember(params: DeleteProjectMember$Params, context?: HttpContext): Observable<void> {
    return this.deleteProjectMember$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProjectSetting()` */
  static readonly GetProjectSettingPath = '/api/project/{projectId}/setting';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectSetting()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectSetting$Response(params: GetProjectSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectSetting>> {
    return getProjectSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectSetting$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectSetting(params: GetProjectSetting$Params, context?: HttpContext): Observable<ProjectSetting> {
    return this.getProjectSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectSetting>): ProjectSetting => r.body)
    );
  }

  /** Path part for operation `updateSastSettingProject()` */
  static readonly UpdateSastSettingProjectPath = '/api/project/{projectId}/setting/sast';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSastSettingProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSastSettingProject$Response(params: UpdateSastSettingProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateSastSettingProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSastSettingProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSastSettingProject(params: UpdateSastSettingProject$Params, context?: HttpContext): Observable<void> {
    return this.updateSastSettingProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateScaSettingProject()` */
  static readonly UpdateScaSettingProjectPath = '/api/project/{projectId}/setting/sca';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateScaSettingProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateScaSettingProject$Response(params: UpdateScaSettingProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateScaSettingProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateScaSettingProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateScaSettingProject(params: UpdateScaSettingProject$Params, context?: HttpContext): Observable<void> {
    return this.updateScaSettingProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getIntegrationProject()` */
  static readonly GetIntegrationProjectPath = '/api/project/{projectId}/integration';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getIntegrationProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIntegrationProject$Response(params: GetIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectIntegration>> {
    return getIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getIntegrationProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIntegrationProject(params: GetIntegrationProject$Params, context?: HttpContext): Observable<ProjectIntegration> {
    return this.getIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectIntegration>): ProjectIntegration => r.body)
    );
  }

  /** Path part for operation `getJiraIntegrationProject()` */
  static readonly GetJiraIntegrationProjectPath = '/api/project/{projectId}/integration/jira';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJiraIntegrationProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJiraIntegrationProject$Response(params: GetJiraIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<JiraProjectSettingResponse>> {
    return getJiraIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJiraIntegrationProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJiraIntegrationProject(params: GetJiraIntegrationProject$Params, context?: HttpContext): Observable<JiraProjectSettingResponse> {
    return this.getJiraIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<JiraProjectSettingResponse>): JiraProjectSettingResponse => r.body)
    );
  }

  /** Path part for operation `updateJiraIntegrationProject()` */
  static readonly UpdateJiraIntegrationProjectPath = '/api/project/{projectId}/integration/jira';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateJiraIntegrationProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateJiraIntegrationProject$Response(params: UpdateJiraIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateJiraIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateJiraIntegrationProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateJiraIntegrationProject(params: UpdateJiraIntegrationProject$Params, context?: HttpContext): Observable<void> {
    return this.updateJiraIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getTeamsIntegrationProject()` */
  static readonly GetTeamsIntegrationProjectPath = '/api/project/{projectId}/integration/teams';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTeamsIntegrationProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamsIntegrationProject$Response(params: GetTeamsIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<TeamsSetting>> {
    return getTeamsIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTeamsIntegrationProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTeamsIntegrationProject(params: GetTeamsIntegrationProject$Params, context?: HttpContext): Observable<TeamsSetting> {
    return this.getTeamsIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<TeamsSetting>): TeamsSetting => r.body)
    );
  }

  /** Path part for operation `updateTeamsIntegrationProject()` */
  static readonly UpdateTeamsIntegrationProjectPath = '/api/project/{projectId}/integration/teams';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTeamsIntegrationProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTeamsIntegrationProject$Response(params: UpdateTeamsIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateTeamsIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTeamsIntegrationProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTeamsIntegrationProject(params: UpdateTeamsIntegrationProject$Params, context?: HttpContext): Observable<void> {
    return this.updateTeamsIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `testTeamsIntegrationProject()` */
  static readonly TestTeamsIntegrationProjectPath = '/api/project/{projectId}/integration/teams/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testTeamsIntegrationProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  testTeamsIntegrationProject$Response(params: TestTeamsIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return testTeamsIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testTeamsIntegrationProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testTeamsIntegrationProject(params: TestTeamsIntegrationProject$Params, context?: HttpContext): Observable<void> {
    return this.testTeamsIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getMailIntegrationProject()` */
  static readonly GetMailIntegrationProjectPath = '/api/project/{projectId}/integration/mail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMailIntegrationProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMailIntegrationProject$Response(params: GetMailIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertSetting>> {
    return getMailIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMailIntegrationProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMailIntegrationProject(params: GetMailIntegrationProject$Params, context?: HttpContext): Observable<AlertSetting> {
    return this.getMailIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<AlertSetting>): AlertSetting => r.body)
    );
  }

  /** Path part for operation `updateMailIntegrationProject()` */
  static readonly UpdateMailIntegrationProjectPath = '/api/project/{projectId}/integration/mail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMailIntegrationProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMailIntegrationProject$Response(params: UpdateMailIntegrationProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateMailIntegrationProject(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMailIntegrationProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMailIntegrationProject(params: UpdateMailIntegrationProject$Params, context?: HttpContext): Observable<void> {
    return this.updateMailIntegrationProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProjectEnvironment()` */
  static readonly GetProjectEnvironmentPath = '/api/project/{projectId}/env/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectEnvironment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectEnvironment$Response(params: GetProjectEnvironment$Params, context?: HttpContext): Observable<StrictHttpResponse<EnvironmentVariablePage>> {
    return getProjectEnvironment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectEnvironment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectEnvironment(params: GetProjectEnvironment$Params, context?: HttpContext): Observable<EnvironmentVariablePage> {
    return this.getProjectEnvironment$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnvironmentVariablePage>): EnvironmentVariablePage => r.body)
    );
  }

  /** Path part for operation `setProjectEnvironment()` */
  static readonly SetProjectEnvironmentPath = '/api/project/{projectId}/env';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setProjectEnvironment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setProjectEnvironment$Response(params: SetProjectEnvironment$Params, context?: HttpContext): Observable<StrictHttpResponse<EnvironmentVariable>> {
    return setProjectEnvironment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setProjectEnvironment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setProjectEnvironment(params: SetProjectEnvironment$Params, context?: HttpContext): Observable<EnvironmentVariable> {
    return this.setProjectEnvironment$Response(params, context).pipe(
      map((r: StrictHttpResponse<EnvironmentVariable>): EnvironmentVariable => r.body)
    );
  }

  /** Path part for operation `removeProjectEnvironment()` */
  static readonly RemoveProjectEnvironmentPath = '/api/project/{projectId}/env/{name}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeProjectEnvironment()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeProjectEnvironment$Response(params: RemoveProjectEnvironment$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removeProjectEnvironment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeProjectEnvironment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeProjectEnvironment(params: RemoveProjectEnvironment$Params, context?: HttpContext): Observable<void> {
    return this.removeProjectEnvironment$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
