/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthSetting } from '../models/auth-setting';
import { createEnvVariable } from '../fn/setting/create-env-variable';
import { CreateEnvVariable$Params } from '../fn/setting/create-env-variable';
import { deleteEnvVariable } from '../fn/setting/delete-env-variable';
import { DeleteEnvVariable$Params } from '../fn/setting/delete-env-variable';
import { getAuthSetting } from '../fn/setting/get-auth-setting';
import { GetAuthSetting$Params } from '../fn/setting/get-auth-setting';
import { getEnvVariable } from '../fn/setting/get-env-variable';
import { GetEnvVariable$Params } from '../fn/setting/get-env-variable';
import { getMailSetting } from '../fn/setting/get-mail-setting';
import { GetMailSetting$Params } from '../fn/setting/get-mail-setting';
import { getSlaSetting } from '../fn/setting/get-sla-setting';
import { GetSlaSetting$Params } from '../fn/setting/get-sla-setting';
import { MailSetting } from '../models/mail-setting';
import { SlaSetting } from '../models/sla-setting';
import { StringPage } from '../models/string-page';
import { testMailSetting } from '../fn/setting/test-mail-setting';
import { TestMailSetting$Params } from '../fn/setting/test-mail-setting';
import { updateAuthSetting } from '../fn/setting/update-auth-setting';
import { UpdateAuthSetting$Params } from '../fn/setting/update-auth-setting';
import { updateMailSetting } from '../fn/setting/update-mail-setting';
import { UpdateMailSetting$Params } from '../fn/setting/update-mail-setting';
import { updateSlaSetting } from '../fn/setting/update-sla-setting';
import { UpdateSlaSetting$Params } from '../fn/setting/update-sla-setting';

@Injectable({ providedIn: 'root' })
export class SettingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMailSetting()` */
  static readonly GetMailSettingPath = '/api/setting/mail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMailSetting()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMailSetting$Response(params?: GetMailSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<MailSetting>> {
    return getMailSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMailSetting$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMailSetting(params?: GetMailSetting$Params, context?: HttpContext): Observable<MailSetting> {
    return this.getMailSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<MailSetting>): MailSetting => r.body)
    );
  }

  /** Path part for operation `updateMailSetting()` */
  static readonly UpdateMailSettingPath = '/api/setting/mail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMailSetting()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMailSetting$Response(params?: UpdateMailSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateMailSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMailSetting$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMailSetting(params?: UpdateMailSetting$Params, context?: HttpContext): Observable<void> {
    return this.updateMailSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `testMailSetting()` */
  static readonly TestMailSettingPath = '/api/setting/mail/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testMailSetting()` instead.
   *
   * This method doesn't expect any request body.
   */
  testMailSetting$Response(params?: TestMailSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return testMailSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testMailSetting$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testMailSetting(params?: TestMailSetting$Params, context?: HttpContext): Observable<string> {
    return this.testMailSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getAuthSetting()` */
  static readonly GetAuthSettingPath = '/api/setting/auth';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAuthSetting()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthSetting$Response(params?: GetAuthSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthSetting>> {
    return getAuthSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAuthSetting$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthSetting(params?: GetAuthSetting$Params, context?: HttpContext): Observable<AuthSetting> {
    return this.getAuthSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthSetting>): AuthSetting => r.body)
    );
  }

  /** Path part for operation `updateAuthSetting()` */
  static readonly UpdateAuthSettingPath = '/api/setting/auth';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAuthSetting()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAuthSetting$Response(params?: UpdateAuthSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateAuthSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAuthSetting$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAuthSetting(params?: UpdateAuthSetting$Params, context?: HttpContext): Observable<void> {
    return this.updateAuthSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getSlaSetting()` */
  static readonly GetSlaSettingPath = '/api/setting/sla';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSlaSetting()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSlaSetting$Response(params?: GetSlaSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<SlaSetting>> {
    return getSlaSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSlaSetting$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSlaSetting(params?: GetSlaSetting$Params, context?: HttpContext): Observable<SlaSetting> {
    return this.getSlaSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<SlaSetting>): SlaSetting => r.body)
    );
  }

  /** Path part for operation `updateSlaSetting()` */
  static readonly UpdateSlaSettingPath = '/api/setting/sla';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSlaSetting()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSlaSetting$Response(params?: UpdateSlaSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateSlaSetting(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSlaSetting$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSlaSetting(params?: UpdateSlaSetting$Params, context?: HttpContext): Observable<void> {
    return this.updateSlaSetting$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getEnvVariable()` */
  static readonly GetEnvVariablePath = '/api/setting/env/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEnvVariable()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getEnvVariable$Response(params?: GetEnvVariable$Params, context?: HttpContext): Observable<StrictHttpResponse<StringPage>> {
    return getEnvVariable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEnvVariable$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getEnvVariable(params?: GetEnvVariable$Params, context?: HttpContext): Observable<StringPage> {
    return this.getEnvVariable$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringPage>): StringPage => r.body)
    );
  }

  /** Path part for operation `createEnvVariable()` */
  static readonly CreateEnvVariablePath = '/api/setting/env';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEnvVariable()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEnvVariable$Response(params?: CreateEnvVariable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return createEnvVariable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEnvVariable$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEnvVariable(params?: CreateEnvVariable$Params, context?: HttpContext): Observable<void> {
    return this.createEnvVariable$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteEnvVariable()` */
  static readonly DeleteEnvVariablePath = '/api/setting/env/{env}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEnvVariable()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEnvVariable$Response(params: DeleteEnvVariable$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteEnvVariable(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEnvVariable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEnvVariable(params: DeleteEnvVariable$Params, context?: HttpContext): Observable<void> {
    return this.deleteEnvVariable$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
