/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createUser } from '../fn/user/create-user';
import { CreateUser$Params } from '../fn/user/create-user';
import { findUserInfoById } from '../fn/user/find-user-info-by-id';
import { FindUserInfoById$Params } from '../fn/user/find-user-info-by-id';
import { listProjectManagerUser } from '../fn/user/list-project-manager-user';
import { ListProjectManagerUser$Params } from '../fn/user/list-project-manager-user';
import { queryUserInfo } from '../fn/user/query-user-info';
import { QueryUserInfo$Params } from '../fn/user/query-user-info';
import { queryUserSummary } from '../fn/user/query-user-summary';
import { QueryUserSummary$Params } from '../fn/user/query-user-summary';
import { sendConfirmEmail } from '../fn/user/send-confirm-email';
import { SendConfirmEmail$Params } from '../fn/user/send-confirm-email';
import { updateUser } from '../fn/user/update-user';
import { UpdateUser$Params } from '../fn/user/update-user';
import { UserInfo } from '../models/user-info';
import { UserInfoPage } from '../models/user-info-page';
import { UserSummary } from '../models/user-summary';
import { UserSummaryPage } from '../models/user-summary-page';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `queryUserSummary()` */
  static readonly QueryUserSummaryPath = '/api/user/public';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `queryUserSummary()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  queryUserSummary$Response(params?: QueryUserSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSummaryPage>> {
    return queryUserSummary(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `queryUserSummary$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  queryUserSummary(params?: QueryUserSummary$Params, context?: HttpContext): Observable<UserSummaryPage> {
    return this.queryUserSummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserSummaryPage>): UserSummaryPage => r.body)
    );
  }

  /** Path part for operation `listProjectManagerUser()` */
  static readonly ListProjectManagerUserPath = '/api/user/project-manager';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listProjectManagerUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  listProjectManagerUser$Response(params?: ListProjectManagerUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserSummary>>> {
    return listProjectManagerUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listProjectManagerUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listProjectManagerUser(params?: ListProjectManagerUser$Params, context?: HttpContext): Observable<Array<UserSummary>> {
    return this.listProjectManagerUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserSummary>>): Array<UserSummary> => r.body)
    );
  }

  /** Path part for operation `queryUserInfo()` */
  static readonly QueryUserInfoPath = '/api/user/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `queryUserInfo()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  queryUserInfo$Response(params?: QueryUserInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfoPage>> {
    return queryUserInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `queryUserInfo$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  queryUserInfo(params?: QueryUserInfo$Params, context?: HttpContext): Observable<UserInfoPage> {
    return this.queryUserInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserInfoPage>): UserInfoPage => r.body)
    );
  }

  /** Path part for operation `findUserInfoById()` */
  static readonly FindUserInfoByIdPath = '/api/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUserInfoById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserInfoById$Response(params: FindUserInfoById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfo>> {
    return findUserInfoById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUserInfoById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserInfoById(params: FindUserInfoById$Params, context?: HttpContext): Observable<UserInfo> {
    return this.findUserInfoById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserInfo>): UserInfo => r.body)
    );
  }

  /** Path part for operation `updateUser()` */
  static readonly UpdateUserPath = '/api/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser$Response(params: UpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfo>> {
    return updateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser(params: UpdateUser$Params, context?: HttpContext): Observable<UserInfo> {
    return this.updateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserInfo>): UserInfo => r.body)
    );
  }

  /** Path part for operation `createUser()` */
  static readonly CreateUserPath = '/api/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser$Response(params?: CreateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfo>> {
    return createUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser(params?: CreateUser$Params, context?: HttpContext): Observable<UserInfo> {
    return this.createUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserInfo>): UserInfo => r.body)
    );
  }

  /** Path part for operation `sendConfirmEmail()` */
  static readonly SendConfirmEmailPath = '/api/user/{userId}/send-confirm-email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendConfirmEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendConfirmEmail$Response(params: SendConfirmEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendConfirmEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendConfirmEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendConfirmEmail(params: SendConfirmEmail$Params, context?: HttpContext): Observable<void> {
    return this.sendConfirmEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
