services:
  codesecure:
    image: ghcr.io/califio/code-secure-dashboard:latest
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_USERNAME: codesecure
      DB_PASSWORD: codesecure
      DB_NAME: codesecure
      SYSTEM_PASSWORD: "" # change system's password. Example: S3cur3Pa$$w0rd
      ACCESS_TOKEN_KEY: "" # change access token key. example: 3afd551d-6882-4a59-8027-09d2f0f723ac
      REFRESH_TOKEN_KEY: "" # change refresh tokenkey. example: 5cf90573-d3ad-4ce8-8801-59f9bc93c703
    ports:
      - "8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-codesecure}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-codesecure}
      PGDATA: /data/postgres
    volumes:
      - codesecure_db:/data/postgres
    ports:
      - "54321:5432"
    restart: unless-stopped

volumes:
  codesecure_db:
