/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserFilter } from '../../models/user-filter';
import { UserInfoPage } from '../../models/user-info-page';

export interface QueryUserInfo$Params {
      body?: UserFilter
}

export function queryUserInfo(http: HttpClient, rootUrl: string, params?: QueryUserInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<UserInfoPage>> {
  const rb = new RequestBuilder(rootUrl, queryUserInfo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserInfoPage>;
    })
  );
}

queryUserInfo.PATH = '/api/user/filter';
