/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JiraSetting } from '../../models/jira-setting';

export interface GetJiraSetting$Params {
}

export function getJiraSetting(http: HttpClient, rootUrl: string, params?: GetJiraSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<JiraSetting>> {
  const rb = new RequestBuilder(rootUrl, getJiraSetting.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<JiraSetting>;
    })
  );
}

getJiraSetting.PATH = '/api/integration/jira';
