/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectFindingFilter } from '../../models/project-finding-filter';
import { ProjectFindingPage } from '../../models/project-finding-page';

export interface GetProjectFindings$Params {
  projectId: string;
      body?: ProjectFindingFilter
}

export function getProjectFindings(http: HttpClient, rootUrl: string, params: GetProjectFindings$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectFindingPage>> {
  const rb = new RequestBuilder(rootUrl, getProjectFindings.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectFindingPage>;
    })
  );
}

getProjectFindings.PATH = '/api/project/{projectId}/finding/filter';
