/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnvironmentVariablePage } from '../../models/environment-variable-page';
import { QueryFilter } from '../../models/query-filter';

export interface GetProjectEnvironment$Params {
  projectId: string;
      body?: QueryFilter
}

export function getProjectEnvironment(http: HttpClient, rootUrl: string, params: GetProjectEnvironment$Params, context?: HttpContext): Observable<StrictHttpResponse<EnvironmentVariablePage>> {
  const rb = new RequestBuilder(rootUrl, getProjectEnvironment.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnvironmentVariablePage>;
    })
  );
}

getProjectEnvironment.PATH = '/api/project/{projectId}/env/filter';
