/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectSettingMetadata } from '../../models/project-setting-metadata';

export interface UpdateProjectSetting$Params {
  projectId: string;
      body?: ProjectSettingMetadata
}

export function updateProjectSetting(http: HttpClient, rootUrl: string, params: UpdateProjectSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectSettingMetadata>> {
  const rb = new RequestBuilder(rootUrl, updateProjectSetting.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectSettingMetadata>;
    })
  );
}

updateProjectSetting.PATH = '/api/project/{projectId}/setting';
