/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadSastFindingRequest } from '../../models/upload-sast-finding-request';
import { UploadSastFindingResponse } from '../../models/upload-sast-finding-response';

export interface UploadSastFinding$Params {
      body?: UploadSastFindingRequest
}

export function uploadSastFinding(http: HttpClient, rootUrl: string, params?: UploadSastFinding$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadSastFindingResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadSastFinding.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadSastFindingResponse>;
    })
  );
}

uploadSastFinding.PATH = '/api/ci/sast-finding';
