/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CiUploadDependencyRequest } from '../../models/ci-upload-dependency-request';
import { CiUploadDependencyResponse } from '../../models/ci-upload-dependency-response';

export interface UploadCiDependency$Params {
      body?: CiUploadDependencyRequest
}

export function uploadCiDependency(http: HttpClient, rootUrl: string, params?: UploadCiDependency$Params, context?: HttpContext): Observable<StrictHttpResponse<CiUploadDependencyResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadCiDependency.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CiUploadDependencyResponse>;
    })
  );
}

uploadCiDependency.PATH = '/api/ci/dependency';
