/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthInfo {
  disablePasswordLogon?: boolean;
  oidcEnable?: boolean;
  oidcProvider?: string | null;
}
