/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthConfig {
  disablePasswordLogon?: boolean | null;
  oidcClientId?: string | null;
  oidcClientSecret?: string | null;
  oidcEnable?: boolean | null;
  oidcEndpoint?: string | null;
  oidcProvider?: string | null;
  oidcScope?: string | null;
}
