/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthSetting {
  disablePasswordLogon: boolean;
  oidcAuthority: string;
  oidcClientId: string;
  oidcClientSecret: string;
  oidcEnable: boolean;
  oidcProvider: string;
  whiteListEmails?: string | null;
}
