/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangeDeadlineFinding {
  currentDate?: string | null;
  previousDate?: string | null;
}
