/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangeStatusFindingMetadata {
  branch?: string | null;
  currentStatus?: string | null;
  previousStatus?: string | null;
}
