/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiPackage } from '../models/ci-package';
import { CiVulnerability } from '../models/ci-vulnerability';
export interface CiPackageInfo {
  package?: CiPackage;
  vulnerabilities?: Array<CiVulnerability> | null;
}
