/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GitAction } from '../models/git-action';
import { ScannerType } from '../models/scanner-type';
import { SourceType } from '../models/source-type';
export interface CiScanRequest {
  commitBranch?: string | null;
  commitHash: string;
  containerImage?: string | null;
  gitAction: GitAction;
  isDefault?: boolean;
  jobUrl: string;
  mergeRequestId?: string | null;
  repoId: string;
  repoName: string;
  repoUrl: string;
  scanTitle: string;
  scanner: string;
  sourceType: SourceType;
  sourceUrl: string;
  targetBranch?: string | null;
  type: ScannerType;
}
