/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiFinding } from '../models/ci-finding';
export interface CiUploadFindingResponse {
  confirmedFindings?: Array<CiFinding> | null;
  fixedFindings?: Array<CiFinding> | null;
  isBlock?: boolean;
  newFindings?: Array<CiFinding> | null;
  openFindings?: Array<CiFinding> | null;
}
