/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiDependencyVulnerability } from '../models/ci-dependency-vulnerability';
import { CiPackage } from '../models/ci-package';
import { CiPackageDependency } from '../models/ci-package-dependency';
export interface CiUploadDependencyRequest {
  packageDependencies?: Array<CiPackageDependency> | null;
  packages: Array<CiPackage>;
  scanId: string;
  vulnerabilities?: Array<CiDependencyVulnerability> | null;
}
