/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiPackageInfo } from '../models/ci-package-info';
export interface CiUploadDependencyResponse {
  isBlock?: boolean;
  packages?: Array<CiPackageInfo> | null;
}
