/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiPackageVulnerabilities } from '../models/ci-package-vulnerabilities';
export interface CiUploadDependencyResponse {
  isBlock?: boolean;
  packages?: Array<CiPackageVulnerabilities> | null;
}
