/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthType } from '../models/auth-type';
import { UserStatus } from '../models/user-status';
export interface CreateUserRequest {
  authType: AuthType;
  email?: string | null;
  roleId: string;
  status: UserStatus;
}
