/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnvironmentVariable } from '../models/environment-variable';
export interface EnvironmentVariablePage {
  count?: number;
  currentPage?: number;
  items?: Array<EnvironmentVariable> | null;
  pageCount?: number;
  size?: number;
}
