/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingLocation } from '../models/finding-location';
export interface FindingMetadata {
  findingFlow?: Array<FindingLocation> | null;
}
