/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangeStatusFindingMetadata } from '../models/change-status-finding-metadata';
import { FindingActivityType } from '../models/finding-activity-type';
export interface FindingActivity {
  avatar?: string | null;
  changeStatusMetadata?: ChangeStatusFindingMetadata;
  comment?: string | null;
  fullname?: string | null;
  metadata?: string | null;
  type?: FindingActivityType;
  userId?: string;
  username?: string | null;
}
