/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindingBranch {
  branch?: string | null;
  commitHash?: string | null;
  isDefault?: boolean;
  scanId?: string;
}
