/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectSource } from '../models/project-source';
export interface FindingProject {
  projectId?: string;
  projectName?: string | null;
  projectSlug?: string | null;
  repoId?: string | null;
  repoUrl?: string | null;
  source?: ProjectSource;
}
