/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangeStatusFinding } from '../models/change-status-finding';
export interface FindingActivityMetadata {
  branch?: string | null;
  changeStatus?: ChangeStatusFinding;
}
