/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangeStatusFinding } from '../models/change-status-finding';
import { FindingScanActivity } from '../models/finding-scan-activity';
export interface FindingActivityMetadata {
  changeStatus?: ChangeStatusFinding;
  scanInfo?: FindingScanActivity;
}
