/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSeverity } from '../models/finding-severity';
import { FindingStatus } from '../models/finding-status';
import { ScannerType } from '../models/scanner-type';
export interface FindingDetail {
  description?: string | null;
  identity?: string | null;
  name?: string | null;
  projectId?: string;
  projectName?: string | null;
  projectSlug?: string | null;
  recommendation?: string | null;
  scanner?: string | null;
  severity?: FindingSeverity;
  sid?: string;
  status?: FindingStatus;
  type?: ScannerType;
}
