/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FindingStatus {
  Open = 'Open',
  Confirmed = 'Confirmed',
  Ignore = 'Ignore',
  Incorrect = 'Incorrect',
  Fixed = 'Fixed'
}
