/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum GitAction {
  CommitBranch = 'CommitBranch',
  MergeRequest = 'MergeRequest',
  CommitTag = 'CommitTag'
}
