/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MailConfig {
  password?: string | null;
  port?: string | null;
  server?: string | null;
  ssl?: boolean | null;
  username?: string | null;
}
