/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MailConfig {
  password: string;
  port: number;
  server: string;
  ssl: boolean;
  username: string;
}
