/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MailSetting {
  password?: string | null;
  port: number;
  server: string;
  useSsl: boolean;
  userName: string;
}
