/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OidcConfig {
  autoRedirect?: boolean;
  clientId?: string | null;
  disablePasswordLogon?: boolean;
  enable?: boolean;
  endpoint?: string | null;
  provider?: string | null;
  scope?: string | null;
}
