/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectSettingMetadata } from '../models/project-setting-metadata';
import { SourceType } from '../models/source-type';
export interface ProjectInfo {
  createdAt?: string;
  id?: string;
  name?: string | null;
  repoId?: string | null;
  repoUrl?: string | null;
  setting?: ProjectSettingMetadata;
  sourceType?: SourceType;
  updatedAt?: string | null;
}
