/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectUser } from '../models/project-user';
export interface ProjectUserPage {
  count?: number;
  currentPage?: number;
  items?: Array<ProjectUser> | null;
  pageCount?: number;
  size?: number;
}
