/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectStatistics {
  critical?: number;
  high?: number;
  info?: number;
  low?: number;
  medium?: number;
  openFinding?: number;
}
