/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectPackageSortField } from '../models/project-package-sort-field';
export interface ProjectPackageFilter {
  desc?: boolean;
  name?: string | null;
  page?: number;
  size?: number;
  sortBy?: ProjectPackageSortField;
}
