/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectSource } from '../models/project-source';
export interface ProjectSummary {
  createdAt?: string;
  id?: string;
  name?: string | null;
  severityCritical?: number;
  severityHigh?: number;
  severityInfo?: number;
  severityLow?: number;
  severityMedium?: number;
  slug?: string | null;
  source?: ProjectSource;
  updatedAt?: string | null;
}
