/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RiskImpact } from '../models/risk-impact';
import { RiskLevel } from '../models/risk-level';
export interface ProjectPackage {
  group?: string | null;
  id?: string;
  location?: string | null;
  name?: string | null;
  riskImpact?: RiskImpact;
  riskLevel?: RiskLevel;
  type?: string | null;
  version?: string | null;
}
