/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SastSetting } from '../models/sast-setting';
import { ScaSetting } from '../models/sca-setting';
export interface ProjectSettingMetadata {
  sastSetting: SastSetting;
  scaSetting: ScaSetting;
}
