/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectSource } from '../models/project-source';
export interface ProjectInfo {
  createdAt?: string;
  id?: string;
  name?: string | null;
  repoId?: string | null;
  repoUrl?: string | null;
  slug?: string | null;
  source?: ProjectSource;
  updatedAt?: string | null;
}
