/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScannerType } from '../models/scanner-type';
export interface ProjectScanner {
  name?: string | null;
  type?: ScannerType;
}
