/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingLocation } from '../models/finding-location';
import { FindingSeverity } from '../models/finding-severity';
export interface SastFinding {
  description: string;
  findingFlow?: Array<FindingLocation> | null;
  identity: string;
  location: FindingLocation;
  name: string;
  recommendation?: string | null;
  ruleId?: string | null;
  severity: FindingSeverity;
}
