/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeverityThreshold {
  critical: number;
  high: number;
  low: number;
  medium: number;
}
