/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SlaConfig {
  slaCritical?: number;
  slaHigh?: number;
  slaInfo?: number;
  slaLow?: number;
  slaMedium?: number;
}
