/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatusSeries {
  acceptedRisk: number;
  confirmed: number;
  fixed: number;
  open: number;
}
