/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamsNotificationSettingRequest {
  active: boolean;
  fixedFindingEvent: boolean;
  newFindingEvent: boolean;
  scanResultEvent: boolean;
  securityAlertEvent: boolean;
  webhook: string;
}
