/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserStatus } from '../models/user-status';
export interface UpdateUserRequest {
  email?: string | null;
  name?: string | null;
  roleId?: string | null;
  status?: UserStatus;
}
