/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SastFinding } from '../models/sast-finding';
export interface UploadSastFindingResponse {
  confirmedFindings?: Array<SastFinding> | null;
  fixedFindings?: Array<SastFinding> | null;
  newFindings?: Array<SastFinding> | null;
  openFindings?: Array<SastFinding> | null;
}
