/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SastFinding } from '../models/sast-finding';
export interface UploadSastFindingRequest {
  findings: Array<SastFinding>;
  scanId: string;
}
