/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthType } from '../models/auth-type';
import { UserStatus } from '../models/user-status';
export interface UserInfo {
  authType?: AuthType;
  avatar?: string | null;
  createdAt?: string;
  email?: string | null;
  enable2Fa?: boolean;
  fullName?: string | null;
  id?: string;
  roleId?: string;
  roleName?: string | null;
  status?: UserStatus;
  updatedAt?: string | null;
  userName?: string | null;
}
