/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getPackageDependencies } from '../fn/dependency/get-package-dependencies';
import { GetPackageDependencies$Params } from '../fn/dependency/get-package-dependencies';
import { PackageInfo } from '../models/package-info';

@Injectable({ providedIn: 'root' })
export class DependencyService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPackageDependencies()` */
  static readonly GetPackageDependenciesPath = '/api/dependency';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPackageDependencies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPackageDependencies$Response(params?: GetPackageDependencies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PackageInfo>>> {
    return getPackageDependencies(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPackageDependencies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPackageDependencies(params?: GetPackageDependencies$Params, context?: HttpContext): Observable<Array<PackageInfo>> {
    return this.getPackageDependencies$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PackageInfo>>): Array<PackageInfo> => r.body)
    );
  }

}
