/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getProjectFindings } from '../fn/project/get-project-findings';
import { GetProjectFindings$Params } from '../fn/project/get-project-findings';
import { getProjects } from '../fn/project/get-projects';
import { GetProjects$Params } from '../fn/project/get-projects';
import { getProjectScans } from '../fn/project/get-project-scans';
import { GetProjectScans$Params } from '../fn/project/get-project-scans';
import { getProjectStatistic } from '../fn/project/get-project-statistic';
import { GetProjectStatistic$Params } from '../fn/project/get-project-statistic';
import { ProjectFindingPage } from '../models/project-finding-page';
import { ProjectScanPage } from '../models/project-scan-page';
import { ProjectStatistics } from '../models/project-statistics';
import { ProjectSummaryPage } from '../models/project-summary-page';

@Injectable({ providedIn: 'root' })
export class ProjectService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProjects()` */
  static readonly GetProjectsPath = '/api/project';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjects$Response(params?: GetProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectSummaryPage>> {
    return getProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjects(params?: GetProjects$Params, context?: HttpContext): Observable<ProjectSummaryPage> {
    return this.getProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectSummaryPage>): ProjectSummaryPage => r.body)
    );
  }

  /** Path part for operation `getProjectStatistic()` */
  static readonly GetProjectStatisticPath = '/api/project/{slug}/statistic';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectStatistic()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectStatistic$Response(params: GetProjectStatistic$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectStatistics>> {
    return getProjectStatistic(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectStatistic$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectStatistic(params: GetProjectStatistic$Params, context?: HttpContext): Observable<ProjectStatistics> {
    return this.getProjectStatistic$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectStatistics>): ProjectStatistics => r.body)
    );
  }

  /** Path part for operation `getProjectScans()` */
  static readonly GetProjectScansPath = '/api/project/{slug}/scan/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectScans()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectScans$Response(params: GetProjectScans$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectScanPage>> {
    return getProjectScans(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectScans$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectScans(params: GetProjectScans$Params, context?: HttpContext): Observable<ProjectScanPage> {
    return this.getProjectScans$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectScanPage>): ProjectScanPage => r.body)
    );
  }

  /** Path part for operation `getProjectFindings()` */
  static readonly GetProjectFindingsPath = '/api/project/{slug}/finding/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectFindings()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectFindings$Response(params: GetProjectFindings$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectFindingPage>> {
    return getProjectFindings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectFindings$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getProjectFindings(params: GetProjectFindings$Params, context?: HttpContext): Observable<ProjectFindingPage> {
    return this.getProjectFindings$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectFindingPage>): ProjectFindingPage => r.body)
    );
  }

}
