/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createUserByAdmin } from '../fn/user/create-user-by-admin';
import { CreateUserByAdmin$Params } from '../fn/user/create-user-by-admin';
import { getUser } from '../fn/user/get-user';
import { GetUser$Params } from '../fn/user/get-user';
import { getUsers } from '../fn/user/get-users';
import { GetUsers$Params } from '../fn/user/get-users';
import { getUsersByAdmin } from '../fn/user/get-users-by-admin';
import { GetUsersByAdmin$Params } from '../fn/user/get-users-by-admin';
import { updateUserByAdmin } from '../fn/user/update-user-by-admin';
import { UpdateUserByAdmin$Params } from '../fn/user/update-user-by-admin';
import { UserDetail } from '../models/user-detail';
import { UserDetailPage } from '../models/user-detail-page';
import { UserSummaryPage } from '../models/user-summary-page';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getUsers()` */
  static readonly GetUsersPath = '/api/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsers$Response(params?: GetUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSummaryPage>> {
    return getUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsers(params?: GetUsers$Params, context?: HttpContext): Observable<UserSummaryPage> {
    return this.getUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserSummaryPage>): UserSummaryPage => r.body)
    );
  }

  /** Path part for operation `createUserByAdmin()` */
  static readonly CreateUserByAdminPath = '/api/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createUserByAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUserByAdmin$Response(params?: CreateUserByAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDetail>> {
    return createUserByAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createUserByAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUserByAdmin(params?: CreateUserByAdmin$Params, context?: HttpContext): Observable<UserDetail> {
    return this.createUserByAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDetail>): UserDetail => r.body)
    );
  }

  /** Path part for operation `getUsersByAdmin()` */
  static readonly GetUsersByAdminPath = '/api/user/by-admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsersByAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByAdmin$Response(params?: GetUsersByAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDetailPage>> {
    return getUsersByAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsersByAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByAdmin(params?: GetUsersByAdmin$Params, context?: HttpContext): Observable<UserDetailPage> {
    return this.getUsersByAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDetailPage>): UserDetailPage => r.body)
    );
  }

  /** Path part for operation `getUser()` */
  static readonly GetUserPath = '/api/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUser$Response(params: GetUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDetail>> {
    return getUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUser(params: GetUser$Params, context?: HttpContext): Observable<UserDetail> {
    return this.getUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDetail>): UserDetail => r.body)
    );
  }

  /** Path part for operation `updateUserByAdmin()` */
  static readonly UpdateUserByAdminPath = '/api/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUserByAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserByAdmin$Response(params: UpdateUserByAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDetail>> {
    return updateUserByAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUserByAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserByAdmin(params: UpdateUserByAdmin$Params, context?: HttpContext): Observable<UserDetail> {
    return this.updateUserByAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDetail>): UserDetail => r.body)
    );
  }

}
