/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlertSetting {
  active?: boolean;
  fixedFindingEvent?: boolean;
  newFindingEvent?: boolean;
  scanCompletedEvent?: boolean;
  scanFailedEvent?: boolean;
  securityAlertEvent?: boolean;
}
