/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiFinding } from '../models/ci-finding';
export interface CiUploadFindingRequest {
  findings?: Array<CiFinding> | null;
  scanId: string;
}
