/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExportType } from '../models/export-type';
import { FindingFilter } from '../models/finding-filter';
export interface ExportFindingRequest {
  exportType: ExportType;
  filter: FindingFilter;
}
