/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingStatus } from '../models/finding-status';
import { GitAction } from '../models/git-action';
export interface FindingScan {
  action?: GitAction;
  branch?: string | null;
  commitHash?: string | null;
  isDefault?: boolean;
  scanId?: string;
  status?: FindingStatus;
  targetBranch?: string | null;
}
