/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IntegrationStatus {
  jira?: boolean;
  jiraWebhook?: boolean;
  mail?: boolean;
  teams?: boolean;
}
