/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JiraProject } from '../models/jira-project';
export interface JiraProjectSettingResponse {
  active: boolean;
  issueType: string;
  jiraProjects?: Array<JiraProject> | null;
  projectKey: string;
}
