/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JiraProjectSetting } from '../models/jira-project-setting';
import { ThresholdSetting } from '../models/threshold-setting';
export interface ProjectSetting {
  jiraSetting?: JiraProjectSetting;
  sastSetting?: ThresholdSetting;
  scaSetting?: ThresholdSetting;
}
