/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GitAction } from '../models/git-action';
export interface ProjectCommitSummary {
  action?: GitAction;
  branch?: string | null;
  commitId?: string;
  isDefault?: boolean;
  targetBranch?: string | null;
}
