/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SeveritySeries } from '../models/severity-series';
import { StatusSeries } from '../models/status-series';
export interface ProjectStatistics {
  openFinding?: number;
  severitySast: SeveritySeries;
  severitySca: SeveritySeries;
  statusSast: StatusSeries;
  statusSca: StatusSeries;
}
