/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommitType } from '../models/commit-type';
import { PackageStatus } from '../models/package-status';
import { RiskImpact } from '../models/risk-impact';
import { RiskLevel } from '../models/risk-level';
export interface ProjectPackage {
  commitBranch?: string | null;
  commitType?: CommitType;
  fixedVersion?: string | null;
  group?: string | null;
  location?: string | null;
  name?: string | null;
  packageId?: string;
  riskImpact?: RiskImpact;
  riskLevel?: RiskLevel;
  status?: PackageStatus;
  targetBranch?: string | null;
  type?: string | null;
  version?: string | null;
}
