/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectFinding } from '../models/project-finding';
export interface ProjectFindingPage {
  count?: number;
  currentPage?: number;
  items?: Array<ProjectFinding> | null;
  pageCount?: number;
  size?: number;
}
