/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSeverity } from '../models/finding-severity';
import { FindingStatus } from '../models/finding-status';
import { ProjectFindingSortField } from '../models/project-finding-sort-field';
export interface ProjectFindingFilter {
  commitId?: string | null;
  desc?: boolean;
  name?: string | null;
  page?: number;
  scanner?: Array<string> | null;
  severity?: FindingSeverity;
  size?: number;
  sortBy?: ProjectFindingSortField;
  status?: Array<FindingStatus> | null;
}
