/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BranchStatusPackage } from '../models/branch-status-package';
import { Packages } from '../models/packages';
import { Vulnerabilities } from '../models/vulnerabilities';
export interface ProjectPackageDetail {
  branchStatus?: Array<BranchStatusPackage> | null;
  dependencies?: Array<Packages> | null;
  info?: Packages;
  location?: string | null;
  vulnerabilities?: Array<Vulnerabilities> | null;
}
