/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SeverityThreshold } from '../models/severity-threshold';
import { ThresholdMode } from '../models/threshold-mode';
export interface SastSetting {
  mode: ThresholdMode;
  severityThreshold: SeverityThreshold;
}
