/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SeveritySeries } from '../models/severity-series';
import { StatusSeries } from '../models/status-series';
import { TopDependency } from '../models/top-dependency';
export interface ScaStatistic {
  severity: SeveritySeries;
  status: StatusSeries;
  topDependencies: Array<TopDependency>;
}
