/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SourceType } from '../models/source-type';
export interface SourceControl {
  id?: string;
  name?: string | null;
  type?: SourceType;
}
