/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StringPage {
  count?: number;
  currentPage?: number;
  items?: Array<string> | null;
  pageCount?: number;
  size?: number;
}
