/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamsSetting {
  active?: boolean;
  fixedFindingEvent?: boolean;
  newFindingEvent?: boolean;
  scanCompletedEvent?: boolean;
  scanFailedEvent?: boolean;
  securityAlertEvent?: boolean;
  webhook?: string | null;
}
