/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketType } from '../models/ticket-type';
export interface TicketTracker {
  active?: boolean;
  type?: TicketType;
}
