/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingStatus } from '../models/finding-status';
export interface UpdateFindingRequest {
  fixDeadline?: string | null;
  recommendation?: string | null;
  status?: FindingStatus;
}
