/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserInfo } from '../models/user-info';
export interface UserInfoPage {
  count?: number;
  currentPage?: number;
  items?: Array<UserInfo> | null;
  pageCount?: number;
  size?: number;
}
